openapi: 3.0.3
info:
  title: Mosad Backend API
  version: 1.0.0
  description: API for authenticating users

servers:
  - url: https://313dce28-5c14-4990-8e70-661764f55665-dev.e1-us-east-azure.choreoapis.dev/mosad-deploying/mosadbackend/v1.0

paths:
  /api/v1/login:
    post:
      summary: User Login
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  format: password
                  example: admin123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: your.jwt.token.here
        '401':
          description: Invalid credentials
        '403':
          description: Forbidden
        '500':
          description: Server error
          
  /api/v1/homestats/cards:
    get:
      summary: Get Home Dashboard Stats
      operationId: getHomeStats
      tags:
        - Dashboard
      responses:
        '200':
          description: Dashboard statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                example:
                  usersCount: 120
                  activeSessions: 15
                  salesToday: 3200
                  newSignups: 5
        '401':
          description: Unauthorized – invalid or expired token
        '403':
          description: Forbidden
        '500':
          description: Server error
          
  /api/v1/homestats/cal:
    get:
      summary: Get calendar duedates for credits
      operationId: getCalendarCreditDueDates
      tags:
        - Dashboard
      responses:
        '200':
          description:  Credit due dates fetched successfully
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Invalid credentials
        '403':
          description: Forbidden
        '500':
          description: Server error
        
  /api/v1/brand:
    get:
      summary: Get Brands by Category
      operationId: getBrands
      tags:
        - Dashboard
      parameters:
        - name: catName
          in: query
          schema:
            type: string
            example: Tyre
          description: category name to filter the brnads
      responses:
        '200':
          description: Brands fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '401':
          description: Invalid credentials
        '403':
          description: Forbidden
        '500':
          description: Server error
  
